#!/usr/bin/env bash
# Cloudify all-in-one machine and containers managing tool 

# STRICT MODE ERROR HANDLING
#set -Eeuo pipefail

# SCRIPT USAGE
function usage(){
cat <<'EOF'
  cloudify [action] [package]
  examples:
       cloudify                     print help
       cloudify help                print help  
       cloudify ls|list             list installable packages 
       cloudify ls|list default     list default packages 
       cloudify i <pkg>             install package
       cloudify i default           install default in termux|station.packages
       cloudify u <pkg>             uninstall package
EOF
}

# CONSTANTES 
PKG_INIT_FILE_DEFAULT="init.sh"
PKG_INIT_FILE_TERMUX="termux.init.sh"
LOCAL_BIN="$HOME"/.local/bin
LOCAL_TMP=/tmp/cloudify
export EDITOR=vim                           # If an editor is needed during install 

# ENVIRONMENT
# Set CLOUDIFY_DIR a defautl value if not already set
# Export it as it is needed in subshells
: "${CLOUDIFY_DIR:=$HOME/cloudify}" && export CLOUDIFY_DIR
# Default assumed platform
export PKG_PLATFORM="ubuntu"

# CLEANUP
# Call clean up function before exiting script
trap cleanup SIGINT SIGTERM ERR EXIT
cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  
  # script cleanup here
  "$CLOUDIFY_DEBUG" || rm -rf "${LOCAL_TMP}"
}


# DEBUG STATE
: "${CLOUDIFY_DEBUG:=false}"                           # If CLOUDIFY_DEBUG isn't set, set it to false. 
export CLOUDIFY_DEBUG                                  # Export it so it's available in subshells

# Print a DEBUG message
function PKG_DEBUG() {
  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG: $1 ***${RESET}" || true
}
# Print a DEBUG message after a new line 
function PKG_DEBUG_LN() {
  $CLOUDIFY_DEBUG && msg "${RED}\n*** DEBUG: $1 ***${RESET}" || true
}

# GENERAL UTILITIES

# Utility function to test if a directory is empty
function emptydir() {
 ls -1qA "$1" | grep -q .
}

# Die gracefully
# Usage: `die "This requirement isn't met" 1
die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "${RED}$msg${RESET}"
  exit "$code"
}

# Farewell message when exiting without error
function printDone() {
  msg "${GREEN}\n********************************************************************************${RESET}"
  msg "${GREEN}  Now please Source ~/.bashrc (Or call rcreload is alias is set)${RESET}"
  msg "${GREEN}********************************************************************************${RESET}"
  msg "${GREEN}  Station cloudified!${RESET}"
  msg "${GREEN}********************************************************************************${RESET}"
}

# Setup colors code for more readable messages
setup_colors() {
  # Setup color codes if we have real terminal on stderr unless colors have been disabled
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    RESET='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    RESET='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

# Print messages with colors
# msg sends its output to stderr (See 12 Factors CLI app principles) and support special color codes
# msg "This is a ${RED}very important${RESET} message, but not a script output value!"
msg() {
  echo >&2 -e "${1-}"
}

# CLOUDIFY API 
# THESE FUNCTION CAN BE CALLED FROM PACKAGE MODULES TO INSTALL SOFTWARE
# Currently Cloudify API is as simple as 2 functions: 'pkg_depends' and 'pkg_in_startuprc' 
#
# pkg_depends:           Most used API function. Declares an explicit dependency. Tries to do its best to install dependencies
# pkg_in_startuprc:      Safely adds to .bashrc (someday to .zshrc) list of single quoted string given as arguments
# pkg_apt_repository:    Safely adds apt repository in apt repositories list 
# pkg_apt_install:       Safely install an apt package   
# pkg_install_release:   Install cloudify package (Run module code if found or calls pkg_apt_install 

# Write lines listed as single-quoted arguments in .bashrc 
# =todo= Make it compatible with zsh shell
function pkg_in_startuprc(){
  PKG_DEBUG_LN "ENV TO SETUP:"
  
  # sed special characters have to be escaped. We're liberal here. 
  pkg_escaped_lines=()
  for pkg_startuprc_line in "${@}"; do
    PKG_DEBUG "Adding '$pkg_startuprc_line'"

    pkg_startuprc_line=$(echo "$pkg_startuprc_line" \
                       | sed 's/\//\\\//g' \
        	             | sed 's/\*/\\*/g' \
	                     | sed 's/\-/\\-/g' \
		                   | sed 's/\!/\\!/g' \
		                   | sed 's/\=/\\=/g' \
		                   | sed 's/\:/\\:/g' \
		                   | sed 's/\[/\\[/g'  | sed 's/\]/\\]/g' \
		                   | sed 's/\\(/\\(/g' | sed 's/\\)/\\)/g')

    pkg_escaped_lines+=( "$pkg_startuprc_line" )
  done;

  PKG_DEBUG_LN "ENV TO SETUP:"
  for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
    PKG_DEBUG "Added '$pkg_startuprc_line'"
  done;
  
  # Reserve cloudify space in bashrc
  PKG_DEBUG_LN "Reserve cloudify space inside bashrc"
  grep -qFx "# CLOUDIFY ENV START" ~/.bashrc || echo -e "\n# CLOUDIFY ENV START\n# CLOUDIFY ENV END"  >> ~/.bashrc
  
  # Remove previous pkg setup
  PKG_DEBUG_LN "Remove existing pkg setup if any"
  for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
    PKG_DEBUG "Remove line: $pkg_startuprc_line"
    sed -in "/$pkg_startuprc_line/d" ~/.bashrc
    PKG_DEBUG "----"
    PKG_DEBUG "What's in there in bashrc?"
    $CLOUDIFY_DEBUG && cat  ~/.bashrc
  done;
  
  # Insert pkg setup 
  PKG_DEBUG_LN "Inserting pkg setup"
  for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
    PKG_DEBUG "Inserting line: $pkg_startuprc_line"
    sed -in "/# CLOUDIFY ENV END/i $pkg_startuprc_line" ~/.bashrc
    PKG_DEBUG "----"
    PKG_DEBUG "What's in there in bashrc?"
    $CLOUDIFY_DEBUG && cat ~/.bashrc
  done;
}

# Add apt source
function pkg_apt_repository() {
  for apt_source in "${@}"; do 
    if ! grep -q "^deb .*${apt_source}" /etc/apt/sources.list.d/*; then
      sudo add-apt-repository "ppa:${apt_source}" -y
    fi
  done
  sudo apt-get -q update 
}


# Install apt package if not already installed
function pkg_apt_install() {
  for pkg in "${@}"; do 
   [[ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]] &&  sudo apt-get -q update
   # =TODO= Parse apt install output to detect error in installation
   if  ! dpkg -l "$pkg" |& grep -q "^ii  $pkg"; then
     PKG_DEBUG_LN "Installing $pkg apt package"
     sudo apt-get -q install "$pkg"  -y || die "Error installing $pkg" 1 
   fi
  done
}

# Install latest release from Github
# =TODO= Add installation from gitlab
# =TODO= Add an argument to force a specific release version  
#        Use 'https://api.github.com/repos/USER/REPO/releases' to list all releases
# =TODO= Should this use 'https://github.com/archf/ghi/blob/master/ghi' ?
function pkg_install_release() {
    # =TODO= be defensive here
    cmd="$1"
    repoId="$2"

    PKG_DEBUG_LN "Retrieving $repoId last release"
    release_url=$(curl -sSL "https://api.github.com/repos/${repoId}/releases/latest" | jq -r ".assets[].browser_download_url" | grep -ie 'linux[-_]amd64' | grep -ie '\.tgz\|\.tar\.gz')
    PKG_DEBUG_LN "Last release url: $release_url"
    
    if [[ ! -z "$cmd"  ]]; then 
      [[ -d /tmp/"$cmd" ]] && rm -rf /tmp/"$cmd"
      mkdir /tmp/"$cmd"
    
      PKG_DEBUG "Extracting $repoId tgz archive. in /tmp/$cmd/"
      curl -sSL "$release_url" | tar -C /tmp/"$cmd"  --strip-components=1  -xzf -

      if emptydir /tmp/"$cmd"; then
         # Contrary to a widely shared practice, this repo doesn't include a top level folder into its release archive 
         curl -sSL "$release_url" | tar -C /tmp/"$cmd"  -xzf -
      fi
      
      PKG_DEBUG "Installing $repoId in /usr/local/"
      (
    
          # Some install archives have an install/setup script. 
          # If that's the case, let it do its thing (A lot of install/setup scripts read the install directory in a prefix variable )
          [[ -f /tmp/"$cmd"/install ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/install && exit 0
          [[ -f /tmp/"$cmd"/install.sh ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/install.sh && exit 0
          [[ -f /tmp/"$cmd"/setup ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/setup && exit 0
          [[ -f /tmp/"$cmd"/setup.sh ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/setup.sh && exit 0
           
          # Some install archive contain directly the binary
          [[ -f /tmp/"$cmd"/"$cmd" ]] && PKG_DEBUG "Installing $cmd binary" && sudo install -Dm 755 /tmp/"$cmd"/"$cmd" /usr/local/bin/ && exit 0
	  
          # The 'install' command doesn't have a recursive option. We use find as a workaround 
          # This will install each file in the archive at corresping path /usr/local
          # Note we're excluding the first level, as this is the place of files, like LICENSE, that shouldn't be installed 
	        # =TODO= harden this part. We should only install some directories like bin, man, etc.
	        for release_dir in 'bin' 'share' 'etc' 'doc'; do
              [[ -d /tmp/"$cmd"/"$release_dir" ]] && PKG_DEBUG "Installing /tmp/$cmd/$release_dir to /usr/local/$release_dir"
              ([[ -d /tmp/"$cmd"/"$release_dir" ]] && cd /tmp/"$cmd"/"$release_dir" && sudo find . -mindepth 1 -type f  -exec install -Dm 755 "{}" "/usr/local/"$release_dir"/{}" \;)
	        done
      )
      PKG_DEBUG "Discarding tmp/$cmd/"
      #rm -rf "/tmp/${cmd}"
    fi
}



# Adds a package dependeny
function pkg_depends() {
  for pkg in "${@}"; do 
    if [[ -f "$CLOUDIFY_DIR"/pkg/"$pkg"/"$pkg_init_file" ]]; then
      PKG_DEBUG "Installing $pkg cloudify package"
      source "$CLOUDIFY_DIR"/pkg/"$pkg"/"$pkg_init_file"
    else
      pkg_apt_install ${pkg}
    fi
  done
}


# SCRIPT ACTIONS
function pkg_list_all() {
  # List all available packages for current platform
  \ls "$CLOUDIFY_DIR"/pkg
}

function pkg_list_defaults() {
  # List default packages for current platform
  # Default packages are lited in ./*.packages files 
  ( for pkg in $(< ${packages_file}); do
      echo ${pkg%%*( )}
    done ) | column 
}

function pkg_show() {
  # Show module code of packages
  for pkg in "$@"; do
    msg "${GREEN}${pkg%%*( )} cloudify package code\n${RESET}"
    msg "${GREEN}>> $CLOUDIFY_DIR/pkg/${pkg%%*( )}/${pkg_init_file}${RESET}"
    cat "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${pkg_init_file}                     # We use bash expansion to trim spaces at the end of the package name
  done
}

function pkg_install_defaults {
  # Install default packages for current platform 
  # Default packages are lited in ./*.packages files 
  for pkg in $(< ${packages_file}); do
    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
    pkg_depends "$pkg"
  done
  printDone
}

function pkg_install {
  # Install specific packages 
  for pkg in "$@"; do
    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
    pkg_depends "$pkg"
  done
  printDone
}

function pkg_uninstall_defaults {
  die "Uninstall package features not ready" 1
}
function pkg_uninstall {
  die "Uninstall package features not ready" 1
}


# Initial configurations before applying script actions
# Ensure tmp folder exist, local bin exist and is in the path 
# Test platform on which sript is running
function preconfigure() {
  # Create local tmp folder 
  [[ -d "$LOCAL_TMP" ]] || mkdir -p "$LOCAL_TMP"
  # Make sure ~/.local/bin exists and is in the path
  [[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"
  [[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"
  
  # Make LOCAL BIN persistent
  # DIRTY HACK! The comment '# CLOUDIFY LOCAL BIN:' is used by cloudify to avoid doublons in .bashrc
  if ! grep -Fq "# CLOUDIFY LOCAL BIN:" $HOME/.bashrc; then 
    echo -e "\n# CLOUDIFY LOCAL BIN: Cloudify may install utility scripts in ~/.local/bin" >> "$HOME"/.bashrc
    echo 'export LOCAL_BIN="$HOME"/.local/bin' >> "$HOME"/.bashrc
    echo '[[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"' >> "$HOME"/.bashrc
    echo '[[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"' >> "$HOME"/.bashrc
  fi 
  
  # Are we on Android Termux or Linux station?
  if [ ! -z "$(pgrep -f com.termux)" ]; then
    export PKG_PLATFORM="termux"
    packages_file=${CLOUDIFY_DIR}/termux.packages
    pkg_init_file=$PKG_INIT_FILE_TERMUX
  else
    packages_file=${CLOUDIFY_DIR}/station.packages
    pkg_init_file=$PKG_INIT_FILE_DEFAULT
  fi
}

# PARSE SCRIPT PARAMETERS 
#  cloudify:                    print help
#  cloudify help:               print help  
#  cloudify ls|list:            list installable packages 
#  cloudify ls|list defaults:   list default packages 
#  cloudify i <pkg>             install package
#  cloudify i default           install default in termux|station.packages
#  cloudify u <pkg>             uninstall package
parse_params () {
  # Parse parameters 
  # default options values 
  action="install"
  
  # Initial setup before running script 
  preconfigure
  
  # Read script parameters
  while :; do
    case "${1-}" in
    -h  | --help | help)
          usage
          break
          ;;
    -v  | --verbose | verbose) set -x ;;
    -n  | --no-color) NO_COLOR=1 ;;
    -l  | ls | list | --list)          
          if [[ -z "${2-}" || "${2-}" == "all" ]]; then
            pkg_list_all 
          elif [[ "${2-}" == "defaults" ]]; then
            pkg_list_defaults
          else
            shift && pkg_show "$@"
          fi
          break ;; 
     i  | install | --install)  
          if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
            pkg_install_defaults
          else
            shift && pkg_install "$@"
          fi
          break ;; 
     u  | uninstall | --uninstall) 
          if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
            pkg_uninstall_defaults
          else
            shift && pkg_uninstall "$@"
          fi
          break ;; 
#   -p  | --param) # Named parameter
#         param="${2-}"
#         shift
#         ;;
    -?*) die "Error: Unknown option '$1'" 1;;
    *) break ;;
    esac
    shift
  done

# Check required params and arguments
#  [[ -z "${param-}" ]] && die "Missing required parameter: param"
#  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"

  # Apply cloudify actions

  return 0
}

# EXECUTE SCRIPT!
parse_params "$@"


## ARCHIVED CODE 

## # Unused but we let it around as it may serve
## PKG_SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

## function main() {
##   # Install packages
##   if [[ -z "$1" || "$1" == "help" ]] ; then
##     # Get help 
##     usage
##   elif [[ ( "$1" == "ls" || "$1" == "list" ) && "$2" == "default" ]]; then
##     # List default packages for current platform
##     # Default packages are lited in ./*.packages files 
##     ( for pkg in $(< ${packages_file}); do
##         echo ${pkg%%*( )}
##       done ) | column 
##   elif [[ ( "$1" == "ls" || "$1" == "list" ) && ( -z "$2" || "$2" == "all" ) ]]; then
##     # List all available packages for current platform
##     \ls "$CLOUDIFY_DIR"/pkg
##   elif [[ ( "$1" == "i" || "$1" == "install" ) &&  "$2" == "default" ]]; then
##     # Install default packages for current platform 
##     # Default packages are lited in ./*.packages files 
##     for pkg in $(< ${packages_file}); do
##       PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
##       if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
##           source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}            # We use bash expansion to trim spaces at the end of the package name
##       else
##           source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                   # We use bash expansion to trim spaces at the end of the package name
##       fi
##     done
##     printDone
##   elif [[ ( "$1" == "i" || "$1" == "install" ) &&  ! -z "$2" ]]; then
##     # Install specific packages 
##     shift                                                                          # Begin argument loop at 2nd argument 
##     for pkg in "$@"; do
##       PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
##       if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
##         source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}              # We use bash expansion to trim spaces at the end of the package name
##       else
##         source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                     # We use bash expansion to trim spaces at the end of the package name
##       fi
##     done
##     printDone
##   else
##     # Get help 
##     usage
##   fi
## }



