#!/usr/bin/env bash
# Cloudify all-in-one machine and containers managing tool 

# STRICT MODE ERROR HANDLING
#set -Eeuo pipefail

#== SCRIPT PATH 
##  This onliner tries to cover all scenarios. It gets the real path of this script bet it executed or sourced directly or through symlinks 
##  =TODO= Compare with [this longer version](https://gist.github.com/TheMengzor/968e5ea87e99d9c41782) and find out if we need it
PKG_SCRIPT_DIR=$(cd "$(dirname $([ -L ${BASH_SOURCE[0]} ] && readlink -f ${BASH_SOURCE[0]} || echo ${BASH_SOURCE[0]}))" &>/dev/null && pwd -P)


#== SCRIPT USAGE
function usage(){
cat <<'EOF'
  cloudify [action] [package]
  examples:
       cloudify help                                   print this usage help 
       cloudify init                                   Initilize cloudify before use (required once per session)
       cloudify --credentials|credentials|c            Sets credentials (local host, remote hosts, github, gitlab)
       cloudify packages|pkgs                          list installable packages 
       cloudify packages|pkgs default                  list default packages 
       cloudify --install|install|i <pkg>              install package on local machine
       cloudify --install|install|i default            install default packages on local machine
       cloudify --uninstall|uninstall|u <pkg>          uninstall package
       cloudify hosts                                  list remote hosts
       cloudify host <host>                            print <host> remote host status
       cloudify launch|run <host>                      launch <host> remote host 
       cloudify delete|del <host>                      remove delete <host> remote host (must be stopped first)
       cloudify delete|del <host> --force              force delete <host> remote host 
       cloudify shell <host>                           open a shell session on <host> remote host
       cloudify --on|on|o <host>                       <host> remote host to run action on
       cloudify --test|test|t                          helper to test code 
EOF
}


#== CONSTANTS 
PKG_INIT_FILE_DEFAULT="init.sh"
PKG_INIT_FILE_TERMUX="termux.init.sh"
LOCAL_BIN="$HOME"/.local/bin
export CLOUDIFY_TMP=/tmp/cloudify
export EDITOR=vim                           # If an editor is needed during install 

#== ENVIRONMENT
# Set CLOUDIFY_DIR a defautl value if not already set
# Export it as it is needed in subshells
: "${CLOUDIFY_DIR:=$HOME/cloudify}" && export CLOUDIFY_DIR
# Default assumed platform
export PKG_PLATFORM="ubuntu"

#== DEBUG STATE
: "${CLOUDIFY_DEBUG:=false}"                           # If CLOUDIFY_DEBUG isn't set, set it to false. 
export CLOUDIFY_DEBUG                                  # Export it so it's available in subshells

#== CLEANUP BEFORE EXIT 
# Call clean up function before exiting script
trap cleanup SIGINT SIGTERM ERR EXIT
function cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  
  # script cleanup here
#  "$CLOUDIFY_DEBUG" || rm -rf "${CLOUDIFY_TMP}"
}


#== DEBUG FUNCTIONS
# Print a DEBUG message

function PKG_DEBUG() {
  #DEBUG_PROMPT='\033[0;33m+(${BASH_SOURCE}:${BASH_LINENO[0]}):\033[0m ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '

#  echo  "DEBUG: ${ORANGE}+(${BASH_SOURCE}:${BASH_LINENO[0]}):${RESET} ${FUNCNAME[0]:+${FUNCNAME[0]}()}${ORANGE} $1${RESET}"

  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG *** ${ORANGE}+(${BASH_SOURCE}:${BASH_LINENO[0]}):${PURPLE} ${FUNCNAME[1]:+${FUNCNAME[1]}()}${ORANGE} $@${RESET}" || true
}

# Print a DEBUG message after a new line 

function PKG_DEBUG_LN() {
#  $CLOUDIFY_DEBUG && msg "${ORANGE}\n*** DEBUG: $1 ***${RESET}" || true
  echo >&2
  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG *** ${ORANGE}+(${BASH_SOURCE}:${BASH_LINENO[0]}):${PURPLE} ${FUNCNAME[1]:+${FUNCNAME[1]}()}${ORANGE} $@${RESET}" || true
}


#== GENERAL UTILITIES

# Simple break command to ease debug
# Pauses until you type enter
function pkg_pause() {
  local _ 
  [[ -z $1 ]] && read -p "Cloudify is paused. Type enter to continue"  _ || read -p "Cloudify is paused at $1. Type enter to continue"  _
}


# Can we define a logical not operator that works as a function and as a command in a pipe?
# =DANGER= Not ready. Don't use!
function not() {
  [[ ! -z "${1-}" ]] && local in=$1 || { local in; read in;}
  [[ -t 1 ]] && {
    [[ "${in-}" == 0 ]] &&  return 1 || return 0; 
  } || {
    [[ "${in-}" == 0 ]] && echo 1 || echo 0; 
  }
}

# Utility function to test if a directory is empty
function emptydir() {
 ls -1qA "$1" | grep -q . && return 1 || return 0 
}

# Die gracefully
# Usage: `die "This requirement isn't met" 1
function die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "${RED}$msg${RESET}"
  exit "$code"
}

# Farewell message when exiting without error
function printDone() {
  msg "${GREEN}\n********************************************************************************${RESET}"
  msg "${GREEN}  Now please Source ~/.bashrc (Or call rcreload is alias is set)${RESET}"
  msg "${GREEN}********************************************************************************${RESET}"
  msg "${GREEN}  Station cloudified!${RESET}"
  msg "${GREEN}********************************************************************************${RESET}"
}

# Setup colors code for more readable messages
function setup_colors() {
  # Setup color codes if we have real terminal on stderr unless colors have been disabled
  PKG_DEBUG Condfiguring colors
  $CLOUDIFY_DEBUG && { 
      [[ -t 2 ]] && PKG_DEBUG Terminal Detected || PKG_DEBUG NO Terminal Detected 
      [[ "${TERM-}" != "dumb"  ]] && PKG_DEBUG Real Terminal Detected || PKG_DEBUG Dumb Terminal Detected 
      [[ -z "${NO_COLOR-}" ]] && PKG_DEBUG Colors enabled || PKG_DEBUG Colors disabled  
  }
  
  if $CLOUDIFY_FORCE_COLORS || ([[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]); then
    RESET='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    RESET='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

# Print messages with colors
# msg sends its output to stderr (See 12 Factors CLI app principles) and support special color codes
# msg "This is a ${RED}very important${RESET} message, but not a script output value!"
function msg() {
  if [[ "${1-}" == "-n" ]]; then
    shift
    echo >&2 -n -e "$@"
  else
    echo >&2 -e "$@"
  fi
}

function msgln() {
  echo >&2 && msg "$@"
}



# Simply prompt the user and read the answer
function prompt2var() {
  local prompt="$1"
  local answervar="$2"
  msg -n "${GREEN}$1${RESET} "
  read "$answervar" 
}

# Prompt the user for a password
# Makes use of 'askpass_stars.sh' script from [antofthy](https://antofthy.gitlab.io/software/askpass_stars_v1.sh.txt)
# Antofty also proposes more evolved scripts that may suit production more (See https://antofthy.gitlab.io/software/#askpass_stars) 
function prompt2pass() {
  local answervar="$1"
  # This utility script reads the password in PWORD 
  local answer=$("$LOCAL_BIN"/askpass_stars.sh)
  export "$answervar"="$answer"
}

# Ask for host credentials
function ask_localhost_credentials(){
  echo
  prompt2var "Host user:" "CLOUDIFY_LOCALHOSTUSER" && export CLOUDIFY_LOCALHOSTUSER 
  # Ensure user password is set
  prompt2pass "CLOUDIFY_LOCALHOSTPWD" && export CLOUDIFY_LOCALHOSTPWD 
  echo
}

# Ask for host credentials
function ask_host_credentials(){
  echo
  prompt2var "Remote Host user:" "CLOUDIFY_HOSTUSER" && export CLOUDIFY_HOSTUSER 
  # Ensure remote host user password is set
  prompt2pass "CLOUDIFY_HOSTPWD" && export CLOUDIFY_HOSTPWD 
  echo
}

# Ask for Github credentials
function ask_github_credentials(){
    echo
    prompt2var "Github user:" "CLOUDIFY_GITHUBUSER" &&  export CLOUDIFY_GITHUBUSER
    # Ensure remote Github password is set
    prompt2pass "CLOUDIFY_GITHUBPWD" && export CLOUDIFY_GITHUBPWD
    echo
}

# Ask for Gitlab credentials
function ask_gitlab_credentials(){
    echo
    prompt2var "Gitlab user:" "CLOUDIFY_GITLABUSER" &&  export CLOUDIFY_GITLABUSER
    # Ensure remote Gitlab user password is set
    prompt2pass "CLOUDIFY_GITLABPWD" && export CLOUDIFY_GITLABPWD
    echo
}


function is_path () {
 # On linux anything can be a path!
 return 0
}

# Parse git urls
# Description: Parse all git urls format
# Syntax: parse_git_url <url> [[url|proto|user|pass|host|domain|subdomain|port|path|account|project]]"
# Example: parse_git_url 'git@github.com/acme/project/repo.git/' 'host,account,project'
#          This writes requested segments on stdout with a 'segment: <segment>' on each line
# Example: parse_git_url ssh://user@host.xz:port/path/to/repo.git/
#          This writes all segments on stdout with a 'segment: <segment>' on each line
# Code copied and tweaked from https://janikvonrotz.ch/2021/03/09/parse-url-in-shell-script/ 
# Supported formats are listed on this [stackoverflow question](https://stackoverflow.com/questions/31801271/what-are-the-supported-git-url-formats)
function parse_git_url () {
    # get protocol
    # if proto isn't given, we're parsing a git format  (user@host.xz:path/to/repo.git)
    [[ ! -z "${1-}" ]] || return 1
    #echo >&2 $1

    local proto="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    [[ -z "${proto-}" || "${proto-}" == *:// ]] || return 1 
    
    # remove the protocol
    local url="$(echo ${1/$proto/})"
    [[ ! -z "${url-}" ]] || return 1
    
    # extract the user (if any)
    local userpass="$(echo $url | grep @ | cut -d@ -f1)"
    local pass="$(echo $userpass | grep : | cut -s -d: -f2)"
    if [ -n "$pass" ]; then
        local user="$(echo $userpass | grep : | cut -d: -f1)"
    else
        user=$userpass
    fi
    
    # remove the user and password
    url="$(echo ${url/$userpass@/})"
    [[ ! -z "${url-}" ]] || return 1
     
    # extract the host and port
    local host_port
    host_port="$(echo ${url} | cut -d/ -f1)"
    [[ ! -z "${host_port-}" ]] || return 1
    
    port="$(echo ${host_port} | cut -s -d: -f2)"

    if [[ ${host_port-} == *:* && ! ${port-} =~ ^[0-9]+$ ]]; then
      [[ -z "${proto-}" ]] && proto="git://"
      host_port="$(echo ${url} | cut -d: -f1)"
      [[ ! -z "${host_port-}" ]] || return 1
      port=""
      host=$host_port
    else
      [[ -z "${proto-}" ]] && proto="https://"
      host="$(echo ${host_port} | cut -d: -f1)"
      [[ ! -z "${host-}" ]] || return 1
    fi
    
#    url                       host_port        port        Prot       host_port        port   host
#    github.com:/toto/tata     github.com:      ''          SSH        github.com        ''     github.com 
#    github.com:toto/tata      github.com:toto  toto        SSH        github.com        ''     github.com
#    github.com:80/titi        github.com:80    80          HTTPS      github.com:80     80     github.com
#    github.com/titi           github.com       ''          HTTPS      github.com        ''     github.com

    
    # extract the path (if any)
    local path
    path="$(echo ${url#$host_port})"
    path="$(echo ${path#:})"

    # extract domain and subdomain

    local levels=$(echo $host | grep -o "\." | wc -l)
    if [ $levels -eq "1" ]; then 
        domain=$host
    fi
    if [ $levels -eq "2" ]; then 
        domain=$(echo $host | awk -F"." '{print $2 "." $3}')
        subdomain=$(echo $host | awk -F"." '{print $1}')
    fi
    [[ ! -z "${domain-}" ]] || return 1
    
    # extract account and project
    local account
    local project

    # TODO just remove any leading slash 
    # account=$(echo $path | sed 's,^/,,' | cut -d/ -f1)  
    # project=$(echo $path | sed 's,^/,,' | cut -s -d/ -f2)  
 
    if [[ "$path" == /* ]]; then
      account=$(echo $path | cut -s -d/ -f2)  
      project=$(echo $path | cut -s -d/ -f3)  
    else
      account=$(echo $path | cut -d/ -f1)  
      project=$(echo $path | cut -s -d/ -f2)  
    fi
    
    if [[ -z "${2-}" ]]; then
      echo -e "url: $url\nproto: $proto\nuser: $user\npass: $pass\nhost_port: $host_port\nhost: $host\ndomain: $domain\nsubdomain: $subdomain\nport: $port\npath: $path\naccount: $account\nproject: $project"
    else
      for f in $(echo $2 | sed "s/,/ /g")
      do
          case $f in
              url)
                  echo $url
                  ;;
              proto)
                  echo $proto
                  ;;
              user)
                  echo $user
                  ;;
              pass)
                  echo $pass
                  ;;
              host)
                  echo $host
                  ;;
              domain)
                  echo $domain
                  ;;
              subdomain)
                  echo $subdomain
                  ;;
              port)
                  echo $port
                  ;;
              path)
                  echo $path
                  ;;
              account)
                  echo $account
                  ;;
              project)
                  echo $project
                  ;;
          esac
      done
    fi
#   Unused
#   local port="$(echo $host_port | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
}

# Is an url a git url ?
# Description: Checks if an url is a git url 
# under the hood, the url is parsed. If the parsing fails, we assume the input isn't an url
function is_git_url () {
 parse_git_url $1 &> /dev/null
}


# Write entry in /etc/hosts 
# =todo= Make it compatible with zsh shell
function add_in_hosts(){
  
  $CLOUDIFY_DEBUG && pkg_pause "break 1"
  # sed special characters have to be escaped. We're liberal here. 
  local escaped_hosts_lines=()
  for host_line in "${@}"; do                     # pkg_startuprc_line
    PKG_DEBUG "Adding '$host_line'" 

    host_line=$(echo "$host_line" \
                       | sed 's/\//\\\//g' \
        	             | sed 's/\*/\\*/g' \
	                     | sed 's/\-/\\-/g' \
		                   | sed 's/\!/\\!/g' \
		                   | sed 's/\=/\\=/g' \
		                   | sed 's/\:/\\:/g' \
		                   | sed 's/\[/\\[/g'  | sed 's/\]/\\]/g' \
		                   | sed 's/\\(/\\(/g' | sed 's/\\)/\\)/g')

   escaped_host_lines+=( "$host_line" )
  done;

  PKG_DEBUG_LN "ENV TO SETUP:"
  for host_line in "${escaped_host_lines[@]}"; do
    PKG_DEBUG "About to insert: '$host_line'"
  done;
  
  # Reserve cloudify space in /etc/hosts 
  $CLOUDIFY_DEBUG && pkg_pause "break 2"
  PKG_DEBUG_LN "Reserve cloudify space inside /etc/hosts"
  grep -qFx "# CLOUDIFY HOSTS START" /etc/hosts || command sudo -kS -p '' sed -i -n -e '$a\\n# CLOUDIFY HOSTS START\n# CLOUDIFY HOSTS END' /etc/hosts <<<$CLOUDIFY_LOCALHOSTPWD
  
  $CLOUDIFY_DEBUG && pkg_pause "break 3"
  # Insert new hosts lines 
  PKG_DEBUG_LN "Inserting host lines"
  for host_line in "${escaped_host_lines[@]}"; do
    PKG_DEBUG "Inserting: $host_line"
    # =TODO= I had to redirect sudo output to /dev/null to avoid the prompt beeing displayed. Even with "-p ''". 
    #        Exact same line above didn't need that. Why that?
    command sudo -kSp '' sed -in "/# CLOUDIFY HOSTS END/i $host_line" /etc/hosts &> /dev/null <<<$CLOUDIFY_LOCALHOSTPWD
    PKG_DEBUG "Inserted: $host_line"
  done

  $CLOUDIFY_DEBUG && pkg_pause "break 4"
}


#== CLOUDIFY API 
# THESE FUNCTION CAN BE CALLED FROM PACKAGE MODULES TO INSTALL SOFTWARE
# Currently Cloudify API is as simple as 2 functions: 'pkg_depends' and 'pkg_in_startuprc' 
#
# pkg_depends:           Most used API function. Declares an explicit dependency. Tries to do its best to install dependencies
# pkg_in_startuprc:      Safely adds to .bashrc (someday to .zshrc) list of single quoted string given as arguments
# pkg_apt_repository:    Safely adds apt repository in apt repositories list 
# pkg_apt_install:       Safely install an apt package   
# pkg_install_release:   Install cloudify package (Run module code if found or calls pkg_apt_install 


# Backup files
# =DANGER= function full of 'rm -rf'!! 
# =TODO= Prevent destructve actions. Example: What happens if called with path '/' ?
pkg_backup() {
  PKG_DEBUG "Running pkg_backup for ${1-}"

  # Do we keep the same name for the target and its target
  same=false; [[ "${1-}" == "--same" ]] && same=true && shift

  if [[ ! -e ${1-} ]]; then
    PKG_DEBUG "File or directory ${1-} not found"
    return 1
  fi
  
  #PKG_DEBUG "Testing same flag"

  # Derive a unique file name for the backup by getting the absolute path of the target and replacing by '/' by '__'

  if "$same"; then
    backup_name=$(basename ${1-}) 
  else 
    backup_name=$(dirname ${1-}) && backup_name="$(basename ${1-})${backup_name//\//@}"
  fi
  backup_name="${CLOUDIFY_TMP}"/backup/${backup_name}

  PKG_DEBUG "Backing up ${1-} to ${backup_name}"

  [[ -d "${CLOUDIFY_TMP}"/backup ]] || PKG_DEBUG "Creating ${CLOUDIFY_TMP}/backup directory" && mkdir -p "${CLOUDIFY_TMP}"/backup 
  rm -rf  "${backup_name}.bak.5"                         2>/dev/null 
  mv      "${backup_name}.bak.4" "${backup_name}.bak.5"  2>/dev/null 
  rm -rf  "${backup_name}.bak.4"                         2>/dev/null 
  mv      "${backup_name}.bak.3" "${backup_name}.bak.4"  2>/dev/null  
  rm -rf  "${backup_name}.bak.3"                         2>/dev/null
  mv      "${backup_name}.bak.2" "${backup_name}.bak.3"  2>/dev/null 
  rm -rf  "${backup_name}.bak.2"                         2>/dev/null
  mv      "${backup_name}.bak.1" "${backup_name}.bak.2"  2>/dev/null
  rm -rf  "${backup_name}.bak.1"                         2>/dev/null
  mv      "${backup_name}.bak"   "${backup_name}.bak.1"  2>/dev/null
  rm -rf  "${backup_name}.bak"                           2>/dev/null
  mv      "${backup_name}"       "${backup_name}.bak"    2>/dev/null
  rm -rf  "${backup_name}"                               2>/dev/null
  cp -paf "$1" "${backup_name}"

  # Now, as we preserved links while copying, if the file/fodler we've backed up is a link, modifying the original will modify the backup...
  # We need to break the original link so any modification of original file won't stain the backup
  # =TODO= Simplify this mess!
  #set -x
  rm -rf  "${backup_name}".atomic                        2>/dev/null
  cp -paL --no-preserve=links "$1" "${backup_name}".atomic 
  rm -rf  "${1}"                               2>/dev/null
  cp -paL --no-preserve=links "${backup_name}".atomic "$1"
  rm -rf  "${backup_name}".atomic                        2>/dev/null
  #set +x

  # Increment backup counter for this file
  [[ -f "${backup_name}.index" ]] || touch "${backup_name}.index" 
  expr $(cat "${backup_name}.index") + 1 > "${backup_name}.index"
}

# pkg_restore uses simple 'mv' to restore files.
# This may mess with ownership and permissions...
# =TODO= use rsync! For the bacup and the restoration.
pkg_restore() {
  PKG_DEBUG "Running Restore"

  [[ ! -d "${CLOUDIFY_TMP}"/backup ]] && PKG_DEBUG "No backup directory found" && return 1 
  
  # Do we keep the same name for the target and its target
  same=false; [[ "${1-}" == "--same" ]] && same=true && shift

  # Derive a unique file name for the backup by getting the absolute path of the target and replacing by '/' by '__'
  "$same" && backup_name=${1-} || backup_name=$(dirname $1) && backup_name="$(basename ${1-})${backup_name//\//@}"
  backup_name="${CLOUDIFY_TMP}"/backup/${backup_name}

  if [[ ! -e "${backup_name-}" && ! -h "${backup_name-}" ]]; then
    PKG_DEBUG "File or directory ${1-} has no backup"
    PKG_DEBUG "File or directory ${backup_name-} doesn't exist"
    return 1
  fi

  PKG_DEBUG "Restoring ${backup_name} to ${1-}"

  trash-put "$1"                                       2>/dev/null 
  mv     "${backup_name}" "$1"                         2>/dev/null 
  rm -rf "${backup_name}"                              2>/dev/null 
  mv     "${backup_name}.bak"  "${backup_name}"        2>/dev/null
  rm -rf "${backup_name}.bak"                          2>/dev/null 
  mv     "${backup_name}.bak.1" "${backup_name}.bak"   2>/dev/null
  rm -rf "${backup_name}.bak.1"                        2>/dev/null 
  mv     "${backup_name}.bak.2" "${backup_name}.bak.1" 2>/dev/null
  rm -rf "${backup_name}.bak.2"                        2>/dev/null 
  mv     "${backup_name}.bak.3" "${backup_name}.bak.2" 2>/dev/null 
  rm -rf "${backup_name}.bak.3"                        2>/dev/null 
  mv     "${backup_name}.bak.4" "${backup_name}.bak.3" 2>/dev/null 
  rm -rf "${backup_name}.bak.4"                        2>/dev/null 
  mv     "${backup_name}.bak.5" "${backup_name}.bak.4" 2>/dev/null 
  
  # Decrement backup counter for this file
  expr $(cat "${backup_name}.index") - 1 > "${backup_name}.index"
  [[ $(cat "${backup_name}.index") == 0 ]] && rm "${backup_name-}.index"
  return 0                             # If we're then everything is ok. Roll back failures are exptected.
}













# Write lines listed as single-quoted arguments in .bashrc 
# =todo= Make it compatible with zsh shell
function pkg_in_startuprc(){
  #PKG_DEBUG_LN "ENV TO SETUP:"
  
  # sed special characters have to be escaped. We're liberal here. 
  pkg_escaped_lines=()
  for pkg_startuprc_line in "${@}"; do
    #PKG_DEBUG "Adding '$pkg_startuprc_line'"

    pkg_startuprc_line=$(echo "$pkg_startuprc_line" \
                       | sed 's/\//\\\//g' \
        	             | sed 's/\*/\\*/g' \
	                     | sed 's/\-/\\-/g' \
		                   | sed 's/\!/\\!/g' \
		                   | sed 's/\=/\\=/g' \
		                   | sed 's/\:/\\:/g' \
		                   | sed 's/\[/\\[/g'  | sed 's/\]/\\]/g' \
		                   | sed 's/\\(/\\(/g' | sed 's/\\)/\\)/g')

    pkg_escaped_lines+=( "$pkg_startuprc_line" )
  done;

  #PKG_DEBUG_LN "ENV TO SETUP:"
  #for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
  #  PKG_DEBUG "Added '$pkg_startuprc_line'"
  #done;
  
  # Reserve cloudify space in bashrc
  #PKG_DEBUG_LN "Reserve cloudify space inside bashrc"
  grep -qFx "# CLOUDIFY ENV START" ~/.bashrc || echo -e "\n# CLOUDIFY ENV START\n# CLOUDIFY ENV END"  >> ~/.bashrc
  
  # Remove previous pkg setup
  #PKG_DEBUG_LN "Remove existing pkg setup if any"
  for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
    #PKG_DEBUG "Remove line: $pkg_startuprc_line"
    sed -in "/$pkg_startuprc_line/d" ~/.bashrc
    #PKG_DEBUG "----"
    #PKG_DEBUG "What's in there in bashrc?"
    #$CLOUDIFY_DEBUG && cat  ~/.bashrc
  done;
  
  # Insert pkg setup 
  #PKG_DEBUG_LN "Inserting pkg setup"
  for pkg_startuprc_line in "${pkg_escaped_lines[@]}"; do
    #PKG_DEBUG "Inserting line: $pkg_startuprc_line"
    sed -in "/# CLOUDIFY ENV END/i $pkg_startuprc_line" ~/.bashrc

    #PKG_DEBUG "----"
    #PKG_DEBUG "What's in there in bashrc?"
    #$CLOUDIFY_DEBUG && cat ~/.bashrc
  done;
}


# Update apt cache
function pkg_apt_update() {
  local hostpwd="${CLOUDIFY_LOCALHOSTPWD-$CLOUDIFY_HOSTPWD}" 
  [[ -z ${hostpwd} ]] && die "Host passord not set"
  if [[ "${1-}" == "--force"  || -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]]; then
    command sudo -kS -p '' apt-get -q update <<< "$hostpwd"
  fi
}

# Add apt source
function pkg_apt_repository() {
  local hostpwd="${CLOUDIFY_LOCALHOSTPWD-$CLOUDIFY_HOSTPWD}" 
  [[ -z ${hostpwd} ]] && die "Host passord not set"
  for apt_source in "${@}"; do 
    if ! grep -q "^deb .*${apt_source}" /etc/apt/sources.list.d/*; then
      command sudo -kS -p '' add-apt-repository "ppa:${apt_source}" -y <<< "$hostpwd"
    fi
  done
  pkg_apt_update --force
}


# Install apt package if not already installed
function pkg_apt_install() {
  local hostpwd="${CLOUDIFY_LOCALHOSTPWD-$CLOUDIFY_HOSTPWD}" 
  [[ -z ${hostpwd} ]] && die "Host passord not set"

  PKG_DEBUG_LN "Installing $pkg apt package"
  for pkg in "${@}"; do 
   pkg_apt_update 
   # =TODO= Parse apt install output to detect error in installation
   if  ! dpkg -l "$pkg" |& grep -q "^ii  $pkg"; then
     command sudo -kS -p '' apt-get -q install "$pkg"  -y  <<< "$hostpwd"
     # If apt-get install failed, we stop cloudify
     # =TODO= Instead of brutally exiting, log the error and continue with next package installations
     local exitcode=$?
     if [ $exitcode -ne 0 ]; then
        die "Error installing $pkg" $exitcode
     fi
   else
     PKG_DEBUG_LN "$pkg apt package already present"
   fi
  done
}

# Install latest release from Github
# =TODO= Add installation from gitlab
# =TODO= Add an argument to force a specific release version  
#        Use 'https://api.github.com/repos/USER/REPO/releases' to list all releases
# =TODO= Should this use 'https://github.com/archf/ghi/blob/master/ghi' ?
function pkg_install_release() {
   local hostpwd="${CLOUDIFY_LOCALHOSTPWD-$CLOUDIFY_HOSTPWD}" 
   [[ -z ${hostpwd} ]] && die "Host passord not set"

    # =TODO= be defensive here
    cmd="$1"
    repoId="$2"

    PKG_DEBUG_LN "Retrieving $repoId last release"
    release_url=$(curl -sSL "https://api.github.com/repos/${repoId}/releases/latest" | jq -r ".assets[].browser_download_url" | grep -ie 'linux[-_]amd64' | grep -ie '\.tgz\|\.tar\.gz')
    PKG_DEBUG_LN "Last release url: $release_url"
    
    if [[ ! -z "$cmd"  ]]; then 
      [[ -d /tmp/"$cmd" ]] && rm -rf /tmp/"$cmd"
      mkdir /tmp/"$cmd"
    
      PKG_DEBUG "Extracting $repoId tgz archive. in /tmp/$cmd/"
      curl -sSL "$release_url" | tar -C /tmp/"$cmd"  --strip-components=1  -xzf -

      if emptydir /tmp/"$cmd"; then
         # Contrary to a widely shared practice, this repo doesn't include a top level folder into its release archive 
         curl -sSL "$release_url" | tar -C /tmp/"$cmd"  -xzf -
      fi
      
      PKG_DEBUG "Installing $repoId in /usr/local/"
      (
          # Some install archives have an install/setup script. 
          # If that's the case, let it do its thing (A lot of install/setup scripts read the install directory in a prefix variable )
          [[ -f /tmp/"$cmd"/install ]] && PKG_DEBUG "Running archive setup script" \
            && command sudo -kS -p '' prefix=/usr/local bash  /tmp/"$cmd"/install <<< "$hostpwd" \
            && exit 0

          [[ -f /tmp/"$cmd"/install.sh ]] && PKG_DEBUG "Running archive setup script" \
            && command sudo -kS -p '' prefix=/usr/local bash  /tmp/"$cmd"/install.sh <<< "$hostpwd" \
            && exit 0

          [[ -f /tmp/"$cmd"/setup ]] && PKG_DEBUG "Running archive setup script" \
            && command sudo -kS -p '' prefix=/usr/local bash  /tmp/"$cmd"/setup <<< "$hostpwd" \
            && exit 0

          [[ -f /tmp/"$cmd"/setup.sh ]] && PKG_DEBUG "Running archive setup script" \
            && command sudo -kS -p '' prefix=/usr/local bash  /tmp/"$cmd"/setup.sh <<< "$hostpwd"   \
            && exit 0
           
          # Some install archive contain directly the binary
          [[ -f /tmp/"$cmd"/"$cmd" ]] && PKG_DEBUG "Installing $cmd binary" \
            && command sudo -kS -p '' install -Dm 755 /tmp/"$cmd"/"$cmd" /usr/local/bin/ <<< "$hostpwd"  \
            && exit 0
	  
          # The 'install' command doesn't have a recursive option. We use find as a workaround 
          # This will install each file in the archive at corresping path /usr/local
          # Note we're excluding the first level, as this is the place of files, like LICENSE, that shouldn't be installed 
	        for release_dir in 'bin' 'share' 'etc' 'doc'; do
              [[ -d /tmp/"$cmd"/"$release_dir" ]] && PKG_DEBUG "Installing /tmp/$cmd/$release_dir to /usr/local/$release_dir"

              if [[ -d /tmp/"$cmd"/"$release_dir" ]]; then
                ( cd /tmp/"$cmd"/"$release_dir" 
                command sudo -kS -p '' find . -mindepth 1 -type f  -exec install -Dm 755 "{}" "/usr/local/"$release_dir"/{}" \; <<< "$hostpwd" )
              fi
	        done
      )
      PKG_DEBUG "Discarding tmp/$cmd/"
      #rm -rf "/tmp/${cmd}"
    fi
}



# Adds a package dependeny
function pkg_depends() {
  for pkg in $@; do 
    PKG_DEBUG "Installing $pkg cloudify package"
    if [[ -f "$CLOUDIFY_DIR/pkg/$pkg/$pkg_init_file" ]]; then
      PKG_DEBUG sourcing "$CLOUDIFY_DIR/pkg/$pkg/$pkg_init_file"
      source "$CLOUDIFY_DIR/pkg/$pkg/$pkg_init_file"

      # Install package scripts in ~/.local/bin
      for script in "$CLOUDIFY_DIR/pkg/$pkg"/*.script; do
	 [[ -e "$script" ]] || continue                        # As per bash normal behaviour, when a glob expansion doesn't match any file,  
	                                                       # the glob pattern itself is processed. This protects against such a case. 
							       # Note that this can also be prevented by setting the 'nullglob' option 
	 script_basename=$(basename $script)
	 PKG_DEBUG copying $script to "$LOCAL_BIN"/${script_basename%.script}
	 cp -paf $script "$LOCAL_BIN"/${script_basename%.script}
      done
    else
      msg "${GREEN}$CLOUDIFY_DIR/pkg/$pkg/$pkg_init_file doesn't exist. Trying apt install.${RESET}" 
      pkg_apt_install ${pkg}
    fi
  done
}




#== CREDENTIALS 
## Cloudify needs user credentials to manage hosts and packages


# Check if needed credentials are set in appropriate environment  variables
# If not, ask for credentials and generate a script that the user will source to set the environment variables

function check_credentials () {
  # Check for credentials environment variables 
  ## sudo user and password, gitlab and github user and password must be set in env variables 
  [[ "${1-}" == "-f" || "${1-}" == "--force" ]] && local force_ask_credentials=true || local force_ask_credentials=false

  local new_credentials=false

  if "$force_ask_credentials" || [[ -z "${CLOUDIFY_LOCALHOSTUSER-}" || -z "${CLOUDIFY_LOCALHOSTPWD-}" || -z "${CLOUDIFY_HOSTUSER-}" || -z "${CLOUDIFY_HOSTPWD-}" ||  -z "${CLOUDIFY_GITHUBUSER-}" || -z "${CLOUDIFY_GITHUBPWD-}" || -z "${CLOUDIFY_GITLABUSER-}" || -z "${CLOUDIFY_GITLABPWD-}" ]]; then
    local new_credentials=true
    msg "${GREEN}Cloudify needs your Host, Github and Gitlab credentials.${RESET}"
    [[ -f /dev/shm/cloudify_credentials ]] && rm -f "/dev/shm/cloudify_credentials"
    touch /dev/shm/cloudify_credentials 
    chmod 600 /dev/shm/cloudify_credentials
  fi

  # Ensure local host user is set
  if "$force_ask_credentials" || [[ -z "${CLOUDIFY_LOCALHOSTUSER-}" || -z "${CLOUDIFY_LOCALHOSTPWD-}" ]]; then
    ask_localhost_credentials
    echo "export CLOUDIFY_LOCALHOSTUSER=$CLOUDIFY_LOCALHOSTUSER" >> /dev/shm/cloudify_credentials
    echo "export CLOUDIFY_LOCALHOSTPWD=$CLOUDIFY_LOCALHOSTPWD" >> /dev/shm/cloudify_credentials
  fi

  # Ensure remote host user is set
  if "$force_ask_credentials" || [[ -z "${CLOUDIFY_HOSTUSER-}" || -z "${CLOUDIFY_HOSTPWD-}" ]]; then
    ask_host_credentials
    echo "export CLOUDIFY_HOSTUSER=$CLOUDIFY_HOSTUSER" >> /dev/shm/cloudify_credentials
    echo "export CLOUDIFY_HOSTPWD=$CLOUDIFY_HOSTPWD" >> /dev/shm/cloudify_credentials
  fi

  # Ensure remote Github user is set
  if "$force_ask_credentials" ||  [[ -z "${CLOUDIFY_GITHUBUSER-}" || -z "${CLOUDIFY_GITHUBPWD-}" ]]; then
    ask_github_credentials
    echo "export CLOUDIFY_GITHUBUSER=$CLOUDIFY_GITHUBUSER" >> /dev/shm/cloudify_credentials
    echo "export CLOUDIFY_GITHUBPWD=$CLOUDIFY_GITHUBPWD" >> /dev/shm/cloudify_credentials
  fi

  # Ensure remote Gitlab host user is set
  if "$force_ask_credentials" ||  [[ -z "${CLOUDIFY_GITLABUSER-}" || -z "${CLOUDIFY_GITLABPWD-}" ]]; then
    ask_gitlab_credentials
    echo "export CLOUDIFY_GITLABUSER=$CLOUDIFY_GITLABUSER" >> /dev/shm/cloudify_credentials
    echo "export CLOUDIFY_GITLABPWD=$CLOUDIFY_GITLABPWD" >> /dev/shm/cloudify_credentials
  fi
  
  if "$new_credentials"; then 
    echo
    msg "${GREEN}A script was generated to store these credentials in environment variables.${RESET}"
    msg "${GREEN}Please execute the following command line:${RESET}"
    msg "source /dev/shm/cloudify_credentials"
  fi
}


#== SHADOWING !
##  Cloudify shadows some bash commands and programs to ensure seamless operations (auto-authentication, idempotence, etc)
##  This way, package init scripts can be naive bash scripts while cloudify ensures high reliability, remote execution, etc


## Sudo Shadowing
#  To call commands requiring password based authentication, we generally supply the password (that is stored in CLOUDIFY_HOSTPWD or CLOUDIFY_LOCALHOSTPWD variable)
#  using a Here String (which uses stdin). Sudo command stdin is often used for normal command processing (like in 'echo <commands> | sudo tee ...') 
#  So to suppy the password to sudo we need to rearrange the way sudo is called, passing everything as arguments to free stdin for password

function sudo() {

  local lineargs=""
  local pipeargs="" 

  if [ -t 0 ]; then
    lineargs="${@}"
  elif [[ -p /dev/stdin ]]; then
    lineargs="${@}"
    pipeargs="$(cat -)"
  else
    lineargs="${@}"
    pipeargs="$(cat -)"
  fi

  if [[ -z $pipeargs ]]; then
    sudocmd="$@"
  else
    sudocmd="echo '$pipeargs' | $lineargs"
  fi

  # As we pass everything, including piped input as arguments to 'bash -c', we can safely supply sudo password using a herestring
  command sudo -kS bash -c "$sudocmd"  &>/dev/null <<< "$CLOUDIFY_HOSTPWD"
}


## Git shadowing

function git_authenticate() {
  local git_remote_url="${1-}"
  [[ -z "${git_remote_url-}" ]] && PKG_DEBUG "Remote url must be non null." return 1


  # first backup current .gitconfig
  pkg_backup "$HOME"/.gitconfig 

  # Only credentials per git domain are supported so far 
  # =TODO= Enable credential per account and per project. 
  local git_domain=$(parse_git_url $git_remote_url domain) 

  case "${git_domain-}" in
     gitlab.com)  
        export GIT_TOKEN=$CLOUDIFY_GITLABPWD
        ;; 
     github.com)  
        export GIT_TOKEN=$CLOUDIFY_GITHUBPWD
        ;; 
     *) die "Git Host $git_domain is not supported'" 1;;
  esac
  echo 'echo $GIT_TOKEN' > $HOME/.git-askpass
  chmod +x $HOME/.git-askpass
  export GIT_ASKPASS=$HOME/.git-askpass

  # use 'insteadOf' git feature to force git to use https connection whatever the git url format used
  command git config --global url."https://api@${git_domain}/".insteadOf "https://${git_domain}/"
  command git config --global url."https://ssh@${git_domain}/".insteadOf "ssh://git@${git_domain}/"
  command git config --global url."https://git@${git_domain}/".insteadOf "git@${git_domain}:"

# git config --global url."https://api@github.com/".insteadOf "https://github.com/"
# git config --global url."https://ssh@github.com/".insteadOf "ssh://git@github.com/"
# git config --global url."https://git@github.com/".insteadOf "git@github.com:"

}

function git_deauthenticate() {

  # Undo our git config modifications 
  pkg_restore "$HOME"/.gitconfig 
}

# Does two remote url refer to the same remote repo? 
function same_git_remote () {
    local remote_url_1="${1-}"
    local remote_url_2="${2-}"

    local url_1; local url_2;
    local host_1;  local host_2; 
    local domain_1;  local domain_2; 
    local subdomain_1;  local subdomain_2; 
    local port_1; local port_2; 
    local account_1;  local account_2; 
    local project_1;  local project_2; 
  
    local _; local segment


    #parse_git_url "${remote_url_1}" 

    # Parsing the output of 'parse_git_utl' to get individual url segments. So meta :)
    # Note without the 'IFS=' prefix, read discards leading and trailing whitespaces. But we need them to correctly parse the segments
    parse_git_url "${remote_url_1}" | {
        IFS= read url_1; segment=$(echo $url_1 | cut -d: -f1); url_1=${url_1#$segment: }
        IFS= read _
        IFS= read _
        IFS= read _
        IFS= read _
        IFS= read host_1;  segment=$(echo $host_1 | cut -d: -f1); host_1=${host_1#$segment: }
        IFS= read domain_1;  segment=$(echo $domain_1 | cut -d: -f1); domain_1=${domain_1#$segment: }
        IFS= read subdomain_1; segment=$(echo $subdomain_1 | cut -d: -f1); subdomain_1=${subdomain_1#$segment: } 
        IFS= read port_1;  segment=$(echo $port_1 | cut -d: -f1); port_1=${port_1#$segment: }
        IFS= read _
        IFS= read account_1;  segment=$(echo $account_1 | cut -d: -f1); account_1=${account_1#$segment: }
        IFS= read project_1;  segment=$(echo $project_1 | cut -d: -f1); project_1=${project_1#$segment: }
  
        #IFS= echo url_1 $url_1
        #IFS= echo host_1 $host_1
        #IFS= echo domain_1 $domain_1
        #IFS= echo subdomain_1 $subdomain_1
        #IFS= echo port_1 $port_1
        #IFS= echo account_1 $account_1
        #IFS= echo project_1 $project_1

        parse_git_url "${remote_url_2}" | {
            IFS= read url_2; segment=$(echo $url_2 | cut -d: -f1); url_2=${url_2#$segment: }
            IFS= read _
            IFS= read _
            IFS= read _
            IFS= read _
            IFS= read host_2;  segment=$(echo $host_2 | cut -d: -f1); host_2=${host_2#$segment: }
            IFS= read domain_2;  segment=$(echo $domain_2 | cut -d: -f1); domain_2=${domain_2#$segment: }
            IFS= read subdomain_2; segment=$(echo $subdomain_2 | cut -d: -f1); subdomain_2=${subdomain_2#$segment: } 
            IFS= read port_2;  segment=$(echo $port_2 | cut -d: -f1); port_2=${port_2#$segment: }
            IFS= read _
            IFS= read account_2;  segment=$(echo $account_2 | cut -d: -f1); account_2=${account_2#$segment: }
            IFS= read project_2;  segment=$(echo $project_2 | cut -d: -f1); project_2=${project_2#$segment: }
  
            #IFS= echo url_2 $url_2
            #IFS= echo host_2 $host_2
            #IFS= echo domain_2 $domain_2
            #IFS= echo subdomain_2 $subdomain_2
            #IFS= echo port_2 $port_2
            #IFS= echo account_2 $account_2
            #IFS= echo project_2 $project_2

            [[ $url_1 == $url_2 ]] && [[ $host_1 == $host_2 ]] && [[ $domain_1 == $domain_2 ]] && [[ $subdomain_1 == $subdomain_2 ]] && [[ $port_1 == $port_2 ]] && [[ $account_1 == $account_2 ]] && [[ $project_1 == $project_2 ]] &&  return 0;
            return 1;
        }
    }
}


function git() {

  # Then   
  local inside_git_repo=false
  local git_remote_url=""
  if [[ "${1-}" == "clone" ]];then
     # We need to get the remote git host by parsing arguments passed to 'git clone'  
     # Any argument that isn't clone or an option, is deemed to be the url to clone
     for arg in "$@"; do
       [[ "${arg-}" != "clone" &&  "${arg-}" != "-*" ]] && { 
         if [[ -z "${git_remote_url}" ]] && is_git_url "${arg-}"; then 
           git_remote_url="${arg-}"
         else
           [[ -z "{git_remote_url}" ]] && { PKG_DEBUG "Unable to git clone: Not a valid git url" &&  return 1; }
           git_repo_path="${arg-}"
           # No validity test here as anything can be a path on linux
           # But we can only clone into an existing folder
           [[ ! -d $(dirname "${arg-}") ]] &&  { PKG_DEBUG "Unable to git clone: path $(dirname ${arg-}) doesn't exist." &&  return 1; }
           break
         fi   
       } 
     done 
     # If the directory exist, we simply update 
     
     # nul 
     # Continue: git will create a sub folder in pwd

     # Not not null, dir doesn't exist
     # Continue: git will create the dir 

     # not null, dir exist. dir  is empty 
     # Continue: git will fill the dir
      
     # not null, dir exist. dir NOT empty 
     # WARNING: if git_repo_url is the same, PULL!
     #          if git_repo_url is not the same. ERROR!

     if [[ -d "$git_repo_path" ]] && ! emptydir "$git_repo_path"; then
       PKG_DEBUG "$git_repo_path directory exist and isn't empty. Pulling updates." 
       ( cd "$git_repo_path"
         inside_git_repo="$(command git rev-parse --is-inside-work-tree 2>/dev/null)"
         $inside_git_repo || { PKG_DEBUG "Can't execute git commands. $git_repo_path isn't a git repo" && return 1; }
         
         if same_git_remote ${git_remote_url} $(command git remote get-url origin); then
             #set -x
             git pull
             #set +x
         else
            PKG_DEBUG "Unable to git clone: Repo $(command git remote get-url origin) different from $git_remote_url you trying to clone." &&  return 1 
         fi
       )
     else
         PKG_DEBUG "$git_repo_path doesn't exist directory exist or is empty. cloning" 
         git_authenticate $git_remote_url
         #set -x
         command git "$@" -v
         #set +x
         git_deauthenticate $git_remote_url
     fi
  else
     # We can directly read remote url 
     inside_git_repo="$(command git rev-parse --is-inside-work-tree 2>/dev/null)"
     if [[ ! "$inside_git_repo" ]]; then
        PKG_DEBUG "Can't execute git commands. $PWD is not inside a git repo."
        return 1
     else
        git_remote_url=$(command git remote get-url origin)
        PKG_DEBUG "Git remote URL: $git_remote_url"
     fi
     git_authenticate $git_remote_url
     PKG_DEBUG "Actual git command executed:" echo git "$@" -v
     #set -x
     command git "$@" -v
     #set +x
     git_deauthenticate $git_remote_url
  fi
}


#== REMOTING
##  Cloudify can execute cloudify package init scripts on remote machine

function cloudify_remote_payload_template() {
  export CLOUDIFY_DEBUG='{{CLOUDIFY_DEBUG}}'
  export CLOUDIFY_HOSTUSER='{{CLOUDIFY_HOSTUSER}}'
  export CLOUDIFY_HOSTPWD='{{CLOUDIFY_HOSTPWD}}'
  export CLOUDIFY_GITHUBUSER='{{CLOUDIFY_GITHUBUSER}}'
  export CLOUDIFY_GITHUBPWD='{{CLOUDIFY_GITHUBPWD}}'
  export CLOUDIFY_GITLABUSER='{{CLOUDIFY_GITLABUSER}}'
  export CLOUDIFY_GITLABPWD='{{CLOUDIFY_GITLABPWD}}'

  bash -c "$(curl -sL scripts.rachid.space/bootstrap/cloudify.sh)"
}

function cloudify_remote() {
  #local host="$1" && shift
  local host="$1" && shift

  if [[ "$host" == "localhost" ]]; then
      cloudify $@  |& sed "s/^/$host: /"  |& sed "s/^$host: $//"
  else
      # Read remote payload template
      local cloudify_remote_payload=$(declare -f cloudify_remote_payload_template | tail -n +3 | head -n -1)
     
      # Load credentials in the payload template
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_DEBUG}}/$CLOUDIFY_DEBUG/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_HOSTUSER}}/$CLOUDIFY_HOSTUSER/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_HOSTPWD}}/$CLOUDIFY_HOSTPWD/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_GITHUBUSER}}/$CLOUDIFY_GITHUBUSER/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_GITHUBPWD}}/$CLOUDIFY_GITHUBPWD/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_GITLABUSER}}/$CLOUDIFY_GITLABUSER/g" <<< "$cloudify_remote_payload")
      cloudify_remote_payload=$(sed "s/{{CLOUDIFY_GITLABPWD}}/$CLOUDIFY_GITLABPWD/g" <<< "$cloudify_remote_payload")
    
      # Add actual cloudify command (plus force output colorization as cloudify won't colorize output when running 
      cloudify_remote_payload="export CLOUDIFY_FORCE_COLORS=true;\n$cloudify_remote_payload; cloudify $@"
    
      PKG_DEBUG "Payload to execute remotely on $host:" 
      # Passwords are replaved by asterisks before printing
      # HACK! Password are recognized only if env variable ends with 'PWD'...
      $CLOUDIFY_DEBUG && msg  "$(sed 's/PWD='\''\(.*\)'\''/PWD='\''***********'\''/g' <<< $cloudify_remote_payload)"

      PKG_DEBUG "SSHing..."
      # The SSH session is launched in the background to parallelize hosts cloudifcation
      # =TODO= Remote hosts key checking has been totally disabled.
      #        It's highly unsafe! Parse ssh messages and prompt the user for decision instead. 
      (ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $host "$cloudify_remote_payload" |& sed "s/^/$host: /"  |& sed "s/^$host: $//") &
      #ssh -tt workify "sudo -kS cat /etc/shadow" <<< "$CLOUDIFY_HOSTPWD"
  fi
} 





#== SCRIPT SUBCOMMANDS 
function pkg_list_all() {
  # List all available packages for current platform
  \ls "$CLOUDIFY_DIR"/pkg
}

function pkg_list_defaults() {
  # List default packages for current platform
  # Default packages are lited in ./*.packages files 
  ( for pkg in $(< ${packages_file}); do
      echo ${pkg%%*( )}
    done ) | column 
}

function pkg_show() {
  # Show module code of packages
  for pkg in "$@"; do
    msg "${GREEN}${pkg%%*( )} cloudify package code\n${RESET}"
    msg "${GREEN}>> $CLOUDIFY_DIR/pkg/${pkg%%*( )}/${pkg_init_file}${RESET}"
    cat "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${pkg_init_file}                     # We use bash expansion to trim spaces at the end of the package name
  done
}

function pkg_install_defaults {
  # Install default packages for current platform 
  # Default packages are lited in ./*.packages files 
  for pkg in $(< ${packages_file}); do
    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
    pkg_depends "$pkg"
  done
  printDone
}

function pkg_install {
  # Install specific packages 
  for pkg in "$@"; do
    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
    pkg_depends "$pkg"
  done
  $SKIPDONEMESSAGE || printDone
}

function pkg_uninstall_defaults {
  die "Uninstall package features not ready" 1
}
function pkg_uninstall {
  die "Uninstall package features not ready" 1
}


# Initial configurations before applying script actions
# Ensure tmp folder exist, local bin exist and is in the path 
# Test platform on which sript is running
function preconfigure() {
  PKG_DEBUG "Running Preconfiguration"
  # Ensure all required credentials are set in proper environment variables
  $SKIPCREDENTIALS || check_credentials

  # Ensure tmp folder exists
  [[ -d "$CLOUDIFY_TMP" ]] || mkdir -p "$CLOUDIFY_TMP"

  # Ensure ~/.local/bin exists and is in the path
  [[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"
  [[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"
  ## Make it persistent 
  ## DIRTY HACK! The comment '# CLOUDIFY LOCAL BIN:' is used by cloudify to avoid doublons in .bashrc
  if ! grep -Fq "# CLOUDIFY LOCAL BIN:" $HOME/.bashrc; then 
    echo -e "\n# CLOUDIFY LOCAL BIN: Cloudify may install utility scripts in ~/.local/bin" >> "$HOME"/.bashrc
    echo 'export LOCAL_BIN="$HOME"/.local/bin' >> "$HOME"/.bashrc
    echo '[[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"' >> "$HOME"/.bashrc
    echo '[[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"' >> "$HOME"/.bashrc
  fi 
  
  # Are we on Android Termux or Linux station?
  if [ ! -z "$(pgrep -f com.termux)" ]; then
    export PKG_PLATFORM="termux"
    packages_file=${CLOUDIFY_DIR}/termux.packages
    pkg_init_file=$PKG_INIT_FILE_TERMUX
    PKG_DEBUG "Package init file name: $pkg_init_file"
  else
    packages_file=${CLOUDIFY_DIR}/station.packages
    pkg_init_file=$PKG_INIT_FILE_DEFAULT
    PKG_DEBUG "Package init file name: $pkg_init_file"
  fi
}


#== TEST CODE!  ############################################# 
#############################################################
# Test code that can be tested w/ 'cloudify test' 
# Use this to test code before inserting it in cloudify 


function inventory {

  # Without filter, return all hosts
  # Remove host duplicates while retaining host order (see awk incantation below)
  {
      [[ $# == 0 ]] && ls -d $CLOUDIFY_DIR/inventory/*/ | xargs -I {} basename {}
    
      for filter in "$@"; do
          if [[ "$filter" != \@* ]]; then
             # If filter is an host, check if it exist
             ls -d $CLOUDIFY_DIR/inventory/"$filter"/  | xargs -I {} basename {}
          else
             # If filter is a tag, filter all hosts with that tag 
             ls -d $CLOUDIFY_DIR/inventory/*/"$filter" | xargs -I {} dirname {} | xargs -I {} basename {}
          fi
      done
  }  | awk '!a[$0]++' 
}

function testCode () {

  echo
  echo inventory:
  echo -e "--------"
  inventory @infra @cluster

}


###################################### END OF TEST CODE!
#############################################################



#== MAIN PARSE SCRIPT PARAMETERS 
#  cloudify:                    print help
#  cloudify help:               print help  
#  cloudify ls|list [all]:      list installable packages 
#  cloudify ls|list defaults:   list default packages 
#  cloudify i <pkg>             install package
#  cloudify i defaults          install default in termux|station.packages
#  cloudify u <pkg>             uninstall package

function cloudify () {
  # Setup colors
  setup_colors

  PKG_DEBUG_LN "*** Cloudify $@"
  host='localhost'
  hosts=""
  hosts_parsing="not started"
  packages=""
  packages_parsing="not started"


  # Parse script parameters
  while :; do
    [[ -z "$1" ]] && break
    case "$1" in
    -h  | --help | help)
          usage
          break
          ;;
    -v  | --verbose | verbose) set -x ;;
    -n  | --no-color) NO_COLOR=1 ;;
    packages | pkgs | pkg)          
          if [[ -z "${2-}" || "${2-}" == "all" ]]; then
            pkg_list_all 
          elif [[ "${2-}" == "defaults" ]]; then
            pkg_list_defaults
          else
            shift && pkg_show "$@"
          fi
          break ;; 
    init)
	  #pkg_pause "installing askpassstars"
	  SKIPCREDENTIALS=true preconfigure
	  SKIPDONEMESSAGE=true pkg_install askpassstars
	  #pkg_pause "installing credentials"
	  cloudify credentials
	  ;;
    hosts)
	  lxc list cloudhorse:
	  ;;
    host)
	  lxc list cloudhorse:$2
	  ;;
    launch | run)
          local hostpwd="${CLOUDIFY_LOCALHOSTPWD}" 
          [[ -z ${hostpwd} ]] && die "Host password not set"
	  local host_image="$2"
          local host="$3"
          local restparams=${@:4} 

          if [[ "$host_image" != *:* ]]; then
              host_image="ubuntu:" 
	      host="$2" 
	      restparams=${@:3}
	  fi

          PKG_DEBUG lxc launch "$host_image" cloudhorse:"$host" -p default $restparams
          lxc launch "$host_image" cloudhorse:"$host" -p default $restparams
          # =TODO= test exit code
          hostip="" 
          while [[ ! $hostip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; do
              hostip=$(lxc list -c4 --format csv cloudhorse:$host | cut -d' ' -f1)
          done
	  $CLOUDIFY_DEBUG && pkg_pause "line before add_in_hosts"
          add_in_hosts "$hostip $host $host.remote" 
	  $CLOUDIFY_DEBUG && pkg_pause "line after add_in_hosts"
          
          ;;
    delete | del)
          local hostpwd="${CLOUDIFY_LOCALHOSTPWD}" 
          [[ -z ${hostpwd} ]] && die "Host password not set"
          host="$2"

          if ! lxc delete cloudhorse:"$host" ${@:3} &>/dev/null; then die "Error deleting $host. Are you sure the host exist?"; fi

          # =TODO= I had to redirect sudo output to /dev/null to avoid the prompt beeing displayed. Even with "-p ''". Why that? 
          command sudo -kS -p '' sed -ri "/^[0-9]+.[0-9]+.[0-9]+.[0-9]+ $host $host.remote$/d" /etc/hosts  &>/dev/null <<< "$hostpwd"
          ;;
    shell)
	  [[ -z $2 ]] && die "Missing host"
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $2
	  ;;
    --on | on | o)  
          # Build hosts list
          [[ $packages_parsing == "started" ]] && die "Cloudify usage error: unexptected on block."
          [[ $hosts_parsing == "started" ]] && die "cloudify usage error: 'on' statement already encountered"

          hosts_parsing="started"
          packages="" 
          hosts=""

          while true; do
            # first, die out on invalid argument
            [[ "$2" == "--on" || "$2" == "on" || "$2" == "o" ||  "$2" == "--help" ||  "$2" == "help" || "$2" == "-h" || "$2" == "--list" || "$2" == "list" || "$2" == "l" || "$2" == "--credentials" || "$2" == "credentials" ||  "$2" == "c" || "$2" == "--test" || "$2" == "test" || "$2" == "t" ]] &&  "Argument syntax error: '$2' invalid inside an 'on' block"
            # If any of these is encountered, there's no more hosts, we can go ahead and setup the hosts
            [[ -z "$2" || "$2" == -* ||  "$2" == "install" || "$2" == "inst" || "$2" == "i" || "$2" == "uninstall" || "$2" == "u" ]] && { 
              [[ -z "$hosts" ]] && die "Cloudify usage error: No host found."
              hosts_parsing="ended" 
              break    # Hosts have been consummed, go ahead and parse next arguments
            }
            [[ -z "$hosts" ]] && hosts="$2" || hosts="$hosts $2"
            shift
          done
          [[ -z "$2" ]] && die "No packages found for hosts: $hosts"
          ;;
     --install | install |inst | i | --uninstall | uninstall | u)  
	  # pkg_pause "executing install subcommand"
          # Build packages list
          [[ $hosts_parsing == "started" ]] && die "Cloudify usage error: unexptected action '$1'"
          [[ -z "$hosts" ]] && hosts="localhost"
          packages_parsing="started"

          local action=''
          case "$1" in
            --install | install |inst | i)
              action='install' 
            ;;
            --uninstall | uninstall | u)  
              action='uninstall' 
          esac

          [[ -z "$packages" ]] &&  packages="--$action" || packages="$packages --$action"


          while true; do
            # first, die out on invalid argument
            [[ "$2" == "--help" ||  "$2" == "help" || "$2" == "-h" || "$2" == "--list" || "$2" == "list" || "$2" == "l" || "$2" == "--credentials" || "$2" == "credentials" ||  "$2" == "c" || "$2" == "--test" || "$2" == "test" || "$2" == "t" ]] &&  die "Argument syntax error: '$2' invalid inside an action block."
            
            # If any of these is encountered, there's no more packages in this package section. Go ahead and parse next package section
            [[ "$2" == "--install" || "$2" == "install" || "$2" == "i" ||  "$2" == "--uninstall" || "$2" == "uninstall" || "$2" == "u" ]] && {
                [[ "$packages" == *--install ]] && die "Cloudify usage error: Empty package section."
              
                [[ "$hosts" == "localhost" ]] && {
                    # Cloudify is executed on localhost. Either because cloudify is executed agains local machine,
                    # we're inside a remote execution. Either way, we can safely execute each package sequentially.
                    # Ensure environment variables are set and set default values otherwise 
                    preconfigure
                    # Go install or uninstall
                    if [[ "$action" == "install" ]]; then 
                        PKG_DEBUG "${YELLOW}pkg_install ${packages/--$action}${RESET}"
                        pkg_install ${packages/--$action}
                    elif [[ "$action" == "uninstall" ]]; then 
                        PKG_DEBUG "${YELLOW}pkg_uninstall ${packages/--$action}${RESET}"
                        pkg_uninstall ${packages/--$action}
                    else
                        die "Unexecpected package action: $action"
                    fi

                    # Make sure each package is processed once
                    packages=""
                 }
                  
                 break    # packages to install have been consummed, go ahead and gather packages to remove 
            } # End of detect install / uninstall test 

            # If any of these is encountered, there's no more packages, we can go ahead and install them 
            [[ -z "$2" || "$2" == "--on" || "$2" == "on" || "$2" == "o" ]] && {
              [[ "$packages" == *--install ]] && die "Cloudify usage error: Empty package section."
              packages_parsing="ended" 
              # Install/Remove packages on hosts
              for host in $hosts; do
                if [[ "$hosts" == "localhost" ]]; then

                    # Ensure environment variables are set and set default values otherwise 
                    # Cloudify is executed on localhost. Either because cloudify is executed agains local machine,
                    # we're inside a remote execution. Either way, we can safely execute each package sequentially.
                    preconfigure
                    # Go install or uninstall
                    if [[ "$action" == "install" ]]; then 
                      PKG_DEBUG "${YELLOW}pkg_install ${packages/--$action}${RESET}"
                      pkg_install ${packages/--$action}
                    elif [[ "$action" == "uninstall" ]]; then 
                      PKG_DEBUG "${YELLOW}pkg_uninstall ${packages/--$action}${RESET}"
                      pkg_uninstall ${packages/--$action}
                    else
                      die "Unexecpected package action: $action"
                    fi
                else
                  PKG_DEBUG_LN "${GREEN}cloudify_remote $host $packages${RESET}"
		  # =TODO= Should this be done in a sub-process? 
                  cloudify_remote "$host" "$packages"
                fi
              done
              break    # All packages have been consummed, go ahead and install/remove them  
            }
            packages="$packages $2"
            shift
          done
          ;;      
     --credentials | credentials | c) 
          check_credentials --force               # Ask all credentials 
          break ;;
     --test | test | t) 
          shift && testCode "$@"
          break ;;
#   -p  | --param) # Named parameter
#         param="${2-}"
#         shift
#         ;;
    -?*) die "Error: Unknown option '$1'" 1;;
    *) break ;;
    esac
    shift
  done

  # Wait until all background tasks return
  msg "${GREEN}Setup of machines in progess...${RESET}"
  wait

  return 0

# Check required params and arguments
#  [[ -z "${param-}" ]] && die "Missing required parameter: param"
#  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
}

#== MAIN: EXECUTE SCRIPT!
cloudify "$@"

