#!/usr/bin/env bash
# guacamole - run phase (ADR-008 split): rewrite software config (.env +
# compose), start the full stack, wait for the webapp, then ensure the RDP
# connection record via the Guacamole REST API. No install guard and never
# destructive: DB data (postgres volume) is untouched here.
#
# Runs after install.sh on `cloudify install` and standalone on
# `cloudify configure` (both in one subshell on install; configure dispatch
# forwards .remote-vars names too, so secrets arrive either way).

pkg_apt_install curl jq

# --- Resolve config (same resolution as install.sh; reruns keep old secrets
# when the env only changes some values) ---
DIR="${CLOUDIFY_GUACAMOLE_DIR:-$HOME/guacamole}"
COMPOSE_FILE="$DIR/docker-compose.yml"

if [[ -f "$DIR/.env" ]]; then
    while IFS= read -r line; do
        key="${line%%=*}"
        val="${line#*=}"
        val="${val%\'}"
        val="${val#\'}"
        [[ -n "${!key:-}" ]] || export "$key=$val"
    done < <(grep -E '^(CLOUDIFY_GUACAMOLE_(DB_PASSWORD|ADMIN_PASSWORD|RDP_PASSWORD|RDP_HOST))=' "$DIR/.env" 2>/dev/null || true)
fi

[[ -n "${CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD:-}" ]] || die "guacamole: CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD is required (env or ~/.config/cloudify/pkgs/guacamole.yaml)"
[[ -n "${CLOUDIFY_GUACAMOLE_DB_PASSWORD:-}" ]] || die "guacamole: CLOUDIFY_GUACAMOLE_DB_PASSWORD is required (env or ~/.config/cloudify/pkgs/guacamole.yaml)"
[[ -n "${CLOUDIFY_GUACAMOLE_RDP_PASSWORD:-}" ]] || die "guacamole: CLOUDIFY_GUACAMOLE_RDP_PASSWORD is required (env or ~/.config/cloudify/pkgs/guacamole.yaml)"
[[ -n "${CLOUDIFY_GUACAMOLE_RDP_HOST:-}" ]] || die "guacamole: CLOUDIFY_GUACAMOLE_RDP_HOST is required (env or ~/.config/cloudify/pkgs/guacamole.yaml)"
for _v in CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD CLOUDIFY_GUACAMOLE_DB_PASSWORD CLOUDIFY_GUACAMOLE_RDP_PASSWORD; do
    if [[ "${!_v:-}" == *"'"* ]] || [[ "${!_v:-}" == *$'\n'* ]] || [[ "${!_v:-}" == *$'\r'* ]]; then
        die "guacamole: $_v contains a single quote or control char - cloudify cannot forward it (see README)"
    fi
done

CLOUDIFY_GUACAMOLE_VERSION="${CLOUDIFY_GUACAMOLE_VERSION:-1.6.0}"
CLOUDIFY_GUACAMOLE_POSTGRES_VERSION="${CLOUDIFY_GUACAMOLE_POSTGRES_VERSION:-16}"
CLOUDIFY_GUACAMOLE_BIND="${CLOUDIFY_GUACAMOLE_BIND:-127.0.0.1}"
CLOUDIFY_GUACAMOLE_PORT="${CLOUDIFY_GUACAMOLE_PORT:-8080}"
CLOUDIFY_GUACAMOLE_DB_NAME="${CLOUDIFY_GUACAMOLE_DB_NAME:-guacamole_db}"
CLOUDIFY_GUACAMOLE_DB_USER="${CLOUDIFY_GUACAMOLE_DB_USER:-guacamole_user}"
CLOUDIFY_GUACAMOLE_ADMIN_USER="${CLOUDIFY_GUACAMOLE_ADMIN_USER:-guacadmin}"
CLOUDIFY_GUACAMOLE_RDP_PORT="${CLOUDIFY_GUACAMOLE_RDP_PORT:-3389}"
CLOUDIFY_GUACAMOLE_RDP_USER="${CLOUDIFY_GUACAMOLE_RDP_USER:-gui}"
CLOUDIFY_GUACAMOLE_CONNECTION_NAME="${CLOUDIFY_GUACAMOLE_CONNECTION_NAME:-GUI}"

mkdir -p "$DIR"

# --- Rewrite software config (.env + compose), then bring the full stack up.
# Config change -> compose recreates the affected container; data untouched. ---
cat > "$DIR/.env" <<ENVEOF
# guacamole pkg - generated by cloudify. Secrets: mode 600, never commit.
GUACAMOLE_VERSION='${CLOUDIFY_GUACAMOLE_VERSION}'
GUACAMOLE_POSTGRES_VERSION='${CLOUDIFY_GUACAMOLE_POSTGRES_VERSION}'
GUACAMOLE_BIND='${CLOUDIFY_GUACAMOLE_BIND}'
GUACAMOLE_PORT='${CLOUDIFY_GUACAMOLE_PORT}'
POSTGRES_DATABASE='${CLOUDIFY_GUACAMOLE_DB_NAME}'
POSTGRES_USER='${CLOUDIFY_GUACAMOLE_DB_USER}'
POSTGRES_PASSWORD='${CLOUDIFY_GUACAMOLE_DB_PASSWORD}'
CLOUDIFY_GUACAMOLE_VERSION='${CLOUDIFY_GUACAMOLE_VERSION}'
CLOUDIFY_GUACAMOLE_POSTGRES_VERSION='${CLOUDIFY_GUACAMOLE_POSTGRES_VERSION}'
CLOUDIFY_GUACAMOLE_BIND='${CLOUDIFY_GUACAMOLE_BIND}'
CLOUDIFY_GUACAMOLE_PORT='${CLOUDIFY_GUACAMOLE_PORT}'
CLOUDIFY_GUACAMOLE_DB_NAME='${CLOUDIFY_GUACAMOLE_DB_NAME}'
CLOUDIFY_GUACAMOLE_DB_USER='${CLOUDIFY_GUACAMOLE_DB_USER}'
CLOUDIFY_GUACAMOLE_DB_PASSWORD='${CLOUDIFY_GUACAMOLE_DB_PASSWORD}'
CLOUDIFY_GUACAMOLE_ADMIN_USER='${CLOUDIFY_GUACAMOLE_ADMIN_USER}'
CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD='${CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD}'
CLOUDIFY_GUACAMOLE_RDP_HOST='${CLOUDIFY_GUACAMOLE_RDP_HOST}'
CLOUDIFY_GUACAMOLE_RDP_PORT='${CLOUDIFY_GUACAMOLE_RDP_PORT}'
CLOUDIFY_GUACAMOLE_RDP_USER='${CLOUDIFY_GUACAMOLE_RDP_USER}'
CLOUDIFY_GUACAMOLE_RDP_PASSWORD='${CLOUDIFY_GUACAMOLE_RDP_PASSWORD}'
CLOUDIFY_GUACAMOLE_CONNECTION_NAME='${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}'
ENVEOF
chmod 600 "$DIR/.env"

cat > "$COMPOSE_FILE" <<'COMPOSEEOF'
services:
  postgres:
    image: postgres:${GUACAMOLE_POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - guacamole_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 30
  guacd:
    image: guacamole/guacd:${GUACAMOLE_VERSION}
    restart: unless-stopped
  guacamole:
    image: guacamole/guacamole:${GUACAMOLE_VERSION}
    restart: unless-stopped
    ports:
      - "${GUACAMOLE_BIND}:${GUACAMOLE_PORT}:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRESQL_ENABLED: "true"
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_DATABASE: ${POSTGRES_DATABASE}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      WEBAPP_CONTEXT: ROOT
    depends_on:
      postgres:
        condition: service_healthy
      guacd:
        condition: service_started
volumes:
  guacamole_pgdata:
COMPOSEEOF

log_info "guacamole: ensuring postgres + guacd (image pull on first run)..."
sudo docker compose -f "$COMPOSE_FILE" up -d --wait postgres guacd

PG_CID="$(sudo docker compose -f "$COMPOSE_FILE" ps -q postgres | head -n1)"
[[ -n "$PG_CID" ]] || die "guacamole: postgres container not found"

# --- Converge the postgres role password (trap 3): the volume keeps the old role
# password when .env changes; ALTER USER via the container's local socket (trust)
# makes the role match the desired config. SQL travels via a 0600 file docker cp'd
# in - never argv, never a pipe through sudo (landmine L2). ---
cat > "$DIR/.dbpass.sql" <<SQLEOF
ALTER USER "${CLOUDIFY_GUACAMOLE_DB_USER}" WITH PASSWORD '${CLOUDIFY_GUACAMOLE_DB_PASSWORD}';
SQLEOF
chmod 600 "$DIR/.dbpass.sql"
sudo docker cp "$DIR/.dbpass.sql" "$PG_CID":/tmp/.dbpass.sql
sudo docker exec "$PG_CID" psql -U "${CLOUDIFY_GUACAMOLE_DB_USER}" -d "${CLOUDIFY_GUACAMOLE_DB_NAME}" -v ON_ERROR_STOP=1 -q -f /tmp/.dbpass.sql \
    || die "guacamole: failed to converge the postgres role password"
sudo docker exec "$PG_CID" rm -f /tmp/.dbpass.sql
rm -f "$DIR/.dbpass.sql"

# --- Converge the Guacamole administrator: exact oracle hash formula
# (sha256(password + UPPERCASE_HEX_SALT)), rename guacadmin to the configured
# admin user. Idempotent; runs on every configure. ---
_SALT_HEX="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n' | tr 'a-f' 'A-F')"
_HASH_HEX="$(printf '%s%s' "${CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD}" "$_SALT_HEX" | sha256sum | cut -d' ' -f1)"
_ADMIN_SQL_USER="$(printf '%s' "${CLOUDIFY_GUACAMOLE_ADMIN_USER}" | sed "s/'/''/g")"
cat > "$DIR/.admin.sql" <<SQLEOF
UPDATE guacamole_user
   SET password_hash = decode('${_HASH_HEX}', 'hex'),
       password_salt = decode('${_SALT_HEX}', 'hex')
 WHERE user_id = (
       SELECT u.user_id FROM guacamole_user u
         JOIN guacamole_entity e ON u.entity_id = e.entity_id
        WHERE e.name IN ('guacadmin', '${_ADMIN_SQL_USER}')
        ORDER BY CASE WHEN e.name = '${_ADMIN_SQL_USER}' THEN 0 ELSE 1 END
        LIMIT 1);
UPDATE guacamole_entity SET name = '${_ADMIN_SQL_USER}' WHERE name = 'guacadmin';
SQLEOF
chmod 600 "$DIR/.admin.sql"
sudo docker cp "$DIR/.admin.sql" "$PG_CID":/tmp/.admin.sql
sudo docker exec "$PG_CID" psql -U "${CLOUDIFY_GUACAMOLE_DB_USER}" -d "${CLOUDIFY_GUACAMOLE_DB_NAME}" -v ON_ERROR_STOP=1 -q -f /tmp/.admin.sql \
    || die "guacamole: admin convergence failed"
sudo docker exec "$PG_CID" rm -f /tmp/.admin.sql
rm -f "$DIR/.admin.sql"

# --- Start/restart the webapp with the converged credentials ---
log_info "guacamole: starting the webapp..."
sudo docker compose -f "$COMPOSE_FILE" up -d guacamole

# --- Wait for the webapp to answer HTTP ---
_base_url="http://${CLOUDIFY_GUACAMOLE_BIND}:${CLOUDIFY_GUACAMOLE_PORT}"
_attempts=0
until curl -fsS -o /dev/null "$_base_url/" 2>/dev/null; do
    _attempts=$((_attempts + 1))
    ((_attempts < 80)) || die "guacamole: webapp not answering on $_base_url after 240s - check 'docker compose -f $COMPOSE_FILE logs guacamole'"
    sleep 3
done

# --- RDP connection record upsert (idempotent). Runs on every configure. ---
_guac_api() {
    # Login -> token + data source (postgresql). Retries while Tomcat warms.
    _attempts=0
    until _login="$(curl -fsS -X POST "$_base_url/api/tokens" \
        --data-urlencode "username=${CLOUDIFY_GUACAMOLE_ADMIN_USER}" \
        --data-urlencode "password=${CLOUDIFY_GUACAMOLE_ADMIN_PASSWORD}" 2>/dev/null)"; do
        _attempts=$((_attempts + 1))
        ((_attempts < 60)) || die "guacamole: admin login failed after 180s - wrong credentials or database state?"
        sleep 3
    done
    _token="$(printf '%s' "$_login" | jq -r '.authToken // empty')"
    _ds="$(printf '%s' "$_login" | jq -r '.dataSource // "postgresql"')"
    [[ -n "$_token" ]] || die "guacamole: API token login returned no authToken"

    # Existing connection id by name, if any.
    _id="$(curl -fsS "$_base_url/api/session/data/${_ds}/connections?token=${_token}" \
        | jq -r --arg n "${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}" \
            'to_entries[] | select(.value.name == $n) | .key' | head -n1)"

    # Parameters that define the RDP target (password deliberately not compared:
    # the API may mask it; rotate by changing any of these or deleting the record).
    _params=$(jq -nc \
        --arg host "${CLOUDIFY_GUACAMOLE_RDP_HOST}" \
        --arg port "${CLOUDIFY_GUACAMOLE_RDP_PORT}" \
        --arg user "${CLOUDIFY_GUACAMOLE_RDP_USER}" \
        --arg pass "${CLOUDIFY_GUACAMOLE_RDP_PASSWORD}" \
        '{hostname: $host, port: $port, username: $user, password: $pass,
          security: "any", "ignore-cert": "true", "resize-method": "display-update"}')

    if [[ -n "$_id" ]]; then
        _current="$(curl -fsS "$_base_url/api/session/data/${_ds}/connections/${_id}/parameters?token=${_token}" \
            | jq -c --arg host "${CLOUDIFY_GUACAMOLE_RDP_HOST}" --arg port "${CLOUDIFY_GUACAMOLE_RDP_PORT}" \
                'select(.hostname == $host and .port == $port)')"
        if [[ -n "$_current" ]]; then
            log_info "guacamole: connection '${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}' already targets ${CLOUDIFY_GUACAMOLE_RDP_HOST}:${CLOUDIFY_GUACAMOLE_RDP_PORT} - unchanged."
            return 0
        fi
        _body=$(jq -nc \
            --arg id "$_id" \
            --arg name "${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}" \
            --argjson params "$_params" \
            '{identifier: $id, parentIdentifier: "ROOT", name: $name, protocol: "rdp", attributes: {}, parameters: $params}')
        curl -fsS -X PUT "$_base_url/api/session/data/${_ds}/connections/${_id}?token=${_token}" \
            -H 'Content-Type: application/json' --data "$_body" >/dev/null \
            || die "guacamole: failed to update connection '${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}'"
        log_info "guacamole: connection '${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}' updated to ${CLOUDIFY_GUACAMOLE_RDP_HOST}:${CLOUDIFY_GUACAMOLE_RDP_PORT}."
    else
        _body=$(jq -nc \
            --arg name "${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}" \
            --argjson params "$_params" \
            '{parentIdentifier: "ROOT", name: $name, protocol: "rdp", attributes: {}, parameters: $params}')
        curl -fsS -X POST "$_base_url/api/session/data/${_ds}/connections?token=${_token}" \
            -H 'Content-Type: application/json' --data "$_body" >/dev/null \
            || die "guacamole: failed to create connection '${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}'"
        log_info "guacamole: connection '${CLOUDIFY_GUACAMOLE_CONNECTION_NAME}' created for ${CLOUDIFY_GUACAMOLE_RDP_HOST}:${CLOUDIFY_GUACAMOLE_RDP_PORT}."
    fi
}

_guac_api
log_info "guacamole: configure phase complete."
