[${CLOUDIFY_RCLONE_REMOTE}]
type = s3
env_auth = false
endpoint = ${CLOUDIFY_RCLONE_REMOTE_ENDPOINT}
access_key_id = ${CLOUDIFY_RCLONE_REMOTE_ACCESSKEYID}
secret_access_key = ${CLOUDIFY_RCLONE_REMOTE_SECRETACCESSKEY}
region = ${CLOUDIFY_RCLONE_REMOTE_REGION}
location_constraint = 
acl = private
force_path_style = false
server_side_encryption = 
storage_class = 
